### ISSUE TITLE
Error from API

### ISSUE THREAD

**Issue by pikachu1992** [pedro2555/vatsim-status-proxy#32]
![image](https://user-images.githubusercontent.com/1645623/56696924-3557c800-66e5-11e9-9e14-73baca393aeb.png)

**Comment by pedro2555** [comment]
Colaca a imagem na descrição em vez de um link. Arrasta, copia e cola, funciona de várias maneiras.

Se for uma mensagem erro, copia a mensagem e coloca na descrição.

Daqui a pouco tou em casa.

**Comment by pedro2555** [comment]
closing since, it is not related to this project directly, and no reproduction information is given.

**Comment by pikachu1992** [comment]
Efectivamente podes ter razao no entanto esse erro aparece inclusive no site da webcomponentes onde esse projecto esta hospedado. logo o erro difinitivamente não e do site onde esta colocado.
Fica aqui o mesmo erro na pagina da webcomponents

![chrome_5Uw1MUuwpq](https://user-images.githubusercontent.com/30056637/56731281-04fa4300-6752-11e9-9eea-b89a0b7c2392.png)
![chrome_MsGLqDeu3f](https://user-images.githubusercontent.com/30056637/56731285-09bef700-6752-11e9-98f7-d9eb0020b5b5.png)

**Comment by pedro2555** [comment]
possible duplicate of #33
